/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package historicos;

import modificacionHistoricos.F_Modificar_Merchandising;
import registros.Registro_Merchan;
import auxiliares.ConexionBaseDatos;
import auxiliares.Fecha;
import configuracion.ColorInterfaz;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Esta clase muestra los registros de ventas de productos promocionales existentes en la Base de Datos.
 * Su utilidad es la de permitir realizar modificaciones o eliminaciones de registros erróneos.
 * @author Daniel Marcos Muñoz
 */
public class F_Historico_Merchandising extends javax.swing.JFrame {

    private static ArrayList<Registro_Merchan> miLista;
    private static F_Modificar_Merchandising modificarMerchan;

    /**
     * Creates new form F_Historico_Merchandising
     */
    public F_Historico_Merchandising() {
        initComponents();
        establecerColor();
        setTitle("Centro de Investigación El Fuerte");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Historico_Merchandising = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelTitulo.setText("Histórico de Ventas de Merchandising");

        tabla_Historico_Merchandising.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NUM_REF", "NUM_PEDIDO", "FECHA", "CONCEPTO", "CANTIDAD", "PRECIO_TOTAL"
            }
        ));
        tabla_Historico_Merchandising.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_Historico_Merchandising);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // NECESITO SACAR LOS NÚMEROS DE REGISTRO DE TODAS LAS FILAS SELECCIONADAS, PARA LUEGO HACER UN DELETE WHERE NUMERO DE REGISTRO COINCIDA CON ELLOS
        int cantidadFilasSeleccionadas = tabla_Historico_Merchandising.getSelectedRowCount();
        if (cantidadFilasSeleccionadas > 0) {
            ArrayList<String> listaEliminar = new ArrayList<>();
            System.out.println("Cantidad filas seleccionadas: " + cantidadFilasSeleccionadas);
            String indice = "0";
            int opcion = JOptionPane.showConfirmDialog(rootPane, "Se van a eliminar " + cantidadFilasSeleccionadas + " registros.\n¿Desea continuar?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                for (int i = 0; i < cantidadFilasSeleccionadas; i++) {
                    indice = (String) tabla_Historico_Merchandising.getValueAt(tabla_Historico_Merchandising.getSelectedRow() + i, 0);
                    listaEliminar.add(indice);
                }
                for (String element : listaEliminar) {
                    eliminarRegistros(Integer.parseInt(element));
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar al menos una fila para eliminarla del registro.", "Información", 1);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int cantCamposSeleccionados = tabla_Historico_Merchandising.getSelectedRowCount();
        if (cantCamposSeleccionados == 1) {
            if (modificarMerchan == null) {
                modificarMerchan = new F_Modificar_Merchandising();
            }
            modificarMerchan.setLocationRelativeTo(this);
            modificarMerchan.setVisible(true);
            int numRefModificar = Integer.valueOf((String) tabla_Historico_Merchandising.getValueAt(tabla_Historico_Merchandising.getSelectedRow(), 0));
            modificarMerchan.cargarDatos(numRefModificar);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una ÚNICA fila para poder modificarla.", "Información", 1);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Historico_Merchandising.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Historico_Merchandising.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Historico_Merchandising.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Historico_Merchandising.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Historico_Merchandising().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnEliminar;
    private static javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel labelTitulo;
    private static javax.swing.JPanel panelFondo;
    private static javax.swing.JTable tabla_Historico_Merchandising;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método extrae de la Base de Datos todos los registros existentes relacionados con la venta de productos promocionales.
     */
    public static void extraerDatosDeBase() {
        miLista = new ArrayList<>();
        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM REGISTRO_MERCHANDISING ORDER BY NUM_REF DESC";
            ResultSet resul = sentencia.executeQuery(sql);
            while (resul.next()) {
                //TIPO ENTRADA, CANTIDAD, EXENCIONES, PRECIO TOTAL
                Registro_Merchan registro = new Registro_Merchan(resul.getInt(1), resul.getInt(2), Fecha.formateaFecha(resul.getDate(3)), resul.getString(4), resul.getInt(5), resul.getFloat(6));
                miLista.add(registro);
            }
        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Merchandising.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al tratar de conectar con la base de datos desde el Histórico de Ventas de Merchandising");
        }

        ConexionBaseDatos.desconexionBaseDatos();
    }

    /**
     * Este método rellena el jTable con los registros de venta de productos promocionales extraídos de la Base de Datos por el método extraerDatosDeBase().
     */
    public static void rellenarTabla() {
        extraerDatosDeBase();
        String matrizDatos[][] = new String[miLista.size()][6];//el segundo número es el número de campos
        for (int i = 0; i < miLista.size(); i++) {
            matrizDatos[i][0] = Integer.toString(miLista.get(i).getNum_ref());
            matrizDatos[i][1] = Integer.toString(miLista.get(i).getRef_pedido());
            matrizDatos[i][2] = miLista.get(i).getFecha();
            matrizDatos[i][3] = miLista.get(i).getConcepto();
            matrizDatos[i][4] = Integer.toString(miLista.get(i).getCantidad());
            matrizDatos[i][5] = Float.toString(miLista.get(i).getPreciTotal());
        }

        tabla_Historico_Merchandising.setModel(new javax.swing.table.DefaultTableModel(
                matrizDatos,
                new String[]{
                    "NUM_REG", "REF_PEDIDO", "FECHA", "CONCEPTO", "CANTIDAD", "PRECIO TOTAL"
                }
        ));
    }

    /**
     * Este método procede a la eliminación, previa confirmación por parte del usuario, de los registros de venta de productos promocionales seleccionados.
     * @param indice Recibe por parámetro la clave primaria del registroa eliminar.
     */
    public void eliminarRegistros(int indice) {
        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "DELETE FROM REGISTRO_MERCHANDISING WHERE NUM_REF =" + indice;
            ResultSet resul = sentencia.executeQuery(sql);
            System.out.println("Se ha eliminado el registro " + indice);
        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Merchandising.class.getName()).log(Level.SEVERE, null, ex);
        }

        rellenarTabla();
    }

    /**
     * Este método gestiona el color de los componentes del registro de venta de productos promocionales en función de las preferencias del usuario.
     */
    public static void establecerColor() {
        ColorInterfaz.dimeColores();
        Color colorFondo = ColorInterfaz.dimeColores()[0];
        Color colorBotones = ColorInterfaz.dimeColores()[1];
        Color colorTexto = ColorInterfaz.dimeColores()[2];

        //Paneles de fondo
        panelFondo.setBackground(colorFondo);

        //Botones
        btnModificar.setBackground(colorBotones);
        btnEliminar.setBackground(colorBotones);

        //Textos
        labelTitulo.setForeground(colorTexto);
        btnModificar.setForeground(colorTexto);
        btnEliminar.setForeground(colorTexto);
        if (modificarMerchan != null) {
            modificarMerchan.establecerColor();
        }
    }
}
