/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modificacionHistoricos;

import Programa.F_Base;
import registros.Registro_Visitante;
import historicos.F_Historico_Visitantes;
import auxiliares.ConexionBaseDatos;
import auxiliares.Fecha;
import configuracion.ColorInterfaz;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Esta clase permite la modificación de los registros de visitantes de la Base de Datos, permitiendo la subsanación de posibles errores.
 * @author Daniel Marcos Muñoz
 */
public class F_Modificar_Visitantes extends javax.swing.JFrame {

    int num_Ref;
    Registro_Visitante registro = null;
    ArrayList<String> listaSexo;
    ArrayList<String> listaRangoEdad;
    ArrayList<String> listaProcedencias;

    /**
     * Creates new form F_Modificar_Visitantes
     */
    public F_Modificar_Visitantes() {
        initComponents();
        establecerColor();
        setTitle("Centro de Investigación El Fuerte");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        lblRef = new javax.swing.JLabel();
        label_numRef = new javax.swing.JLabel();
        lblRefVis = new javax.swing.JLabel();
        spn_refVisita = new javax.swing.JSpinner();
        lblFecha = new javax.swing.JLabel();
        calendar_fecha = new rojeru_san.componentes.RSDateChooser();
        lblCantidad = new javax.swing.JLabel();
        spn_Cantidad = new javax.swing.JSpinner();
        lblSexo = new javax.swing.JLabel();
        cmb_refSexo = new javax.swing.JComboBox<>();
        lblRangoEdad = new javax.swing.JLabel();
        cmb_rangoEdad = new javax.swing.JComboBox<>();
        lblProcedenciaInter = new javax.swing.JLabel();
        chb_Internacional = new javax.swing.JCheckBox();
        lblProcedencia = new javax.swing.JLabel();
        cmb_procedencia = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Modificar Registro");

        panelContenedor.setLayout(new java.awt.GridLayout(8, 2));

        lblRef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRef.setText("Nº Referencia:");
        panelContenedor.add(lblRef);

        label_numRef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_numRef.setText("-");
        panelContenedor.add(label_numRef);

        lblRefVis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRefVis.setText("Referencia de Visita:");
        panelContenedor.add(lblRefVis);

        spn_refVisita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spn_refVisita.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        panelContenedor.add(spn_refVisita);

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");
        panelContenedor.add(lblFecha);

        calendar_fecha.setFuente(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelContenedor.add(calendar_fecha);

        lblCantidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad:");
        panelContenedor.add(lblCantidad);

        spn_Cantidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spn_Cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        panelContenedor.add(spn_Cantidad);

        lblSexo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSexo.setText("Sexo:");
        panelContenedor.add(lblSexo);

        cmb_refSexo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmb_refSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelContenedor.add(cmb_refSexo);

        lblRangoEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRangoEdad.setText("Rango de edad:");
        panelContenedor.add(lblRangoEdad);

        cmb_rangoEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmb_rangoEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelContenedor.add(cmb_rangoEdad);

        lblProcedenciaInter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProcedenciaInter.setText("Procedencia Internacional:");
        panelContenedor.add(lblProcedenciaInter);

        chb_Internacional.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chb_Internacional.setText("Internacional");
        chb_Internacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_InternacionalActionPerformed(evt);
            }
        });
        panelContenedor.add(chb_Internacional);

        lblProcedencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProcedencia.setText("Procedencia:");
        panelContenedor.add(lblProcedencia);

        cmb_procedencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmb_procedencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelContenedor.add(cmb_procedencia);

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void chb_InternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_InternacionalActionPerformed
        // TODO add your handling code here:
        cargarComboBoxProcedencias();
    }//GEN-LAST:event_chb_InternacionalActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar el registro seleccionado?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            String internacional = (chb_Internacional.isSelected()) ? "Y" : "N";
            String datosActualizacion = "UPDATE REGISTRO_VISITANTES SET REF_VISITA = " + spn_refVisita.getValue()
                    + ", FECHA = '" + Fecha.formateaFecha(calendar_fecha.getDatoFecha()) + "'"
                    + ", CANTIDAD = " + spn_Cantidad.getValue()
                    + ", REF_SEXO = '" + cmb_refSexo.getSelectedItem() + "'"
                    + ", REF_RANGOEDAD = '" + cmb_rangoEdad.getSelectedItem() + "'"
                    + ", PROCEDENCIA_INTERNACIONAL = '" + internacional + "'"
                    + ", PROCEDENCIA = '" + cmb_procedencia.getSelectedItem() + "'"
                    + " WHERE NUM_REF = " + num_Ref;
            System.out.println(datosActualizacion);
            PreparedStatement sentencia;
            try {
                sentencia = conexion.prepareStatement(datosActualizacion);
                sentencia.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Registro modificado con éxito", "Información", 3);
                F_Historico_Visitantes.rellenarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(F_Historico_Visitantes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Los datos introducidos no son válidos.\nEl registro NO ha sido modificado.", "Error", 2);
            }
            ConexionBaseDatos.desconexionBaseDatos();
            dispose();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Modificar_Visitantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnCancelar;
    private static javax.swing.JButton btnModificar;
    private rojeru_san.componentes.RSDateChooser calendar_fecha;
    private static javax.swing.JCheckBox chb_Internacional;
    private javax.swing.JComboBox<String> cmb_procedencia;
    private javax.swing.JComboBox<String> cmb_rangoEdad;
    private javax.swing.JComboBox<String> cmb_refSexo;
    private static javax.swing.JLabel labelTitulo;
    private static javax.swing.JLabel label_numRef;
    private static javax.swing.JLabel lblCantidad;
    private static javax.swing.JLabel lblFecha;
    private static javax.swing.JLabel lblProcedencia;
    private static javax.swing.JLabel lblProcedenciaInter;
    private static javax.swing.JLabel lblRangoEdad;
    private static javax.swing.JLabel lblRef;
    private static javax.swing.JLabel lblRefVis;
    private static javax.swing.JLabel lblSexo;
    private static javax.swing.JPanel panelContenedor;
    private static javax.swing.JPanel panelFondo;
    private javax.swing.JSpinner spn_Cantidad;
    private javax.swing.JSpinner spn_refVisita;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método recupera de la Base de Datos la información relativa al registro a modificar, y la carga en los componentes del formulario para que el usuario la pueda modificar.
     * @param numRef Recibe por parámetro la clave primaria del registro a modificar.
     */
    public void cargarDatos(int numRef) { //consulta a la base de datos con el NUM_REF de la celda seleccionada en la tabla del registro
        cargarComboBoxSexo();
        cargarComboBoxEdad();

        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM REGISTRO_VISITANTES WHERE NUM_REF = " + numRef;
            ResultSet resul = sentencia.executeQuery(sql);

            while (resul.next()) {
                registro = new Registro_Visitante(resul.getInt(1), resul.getInt(2), resul.getDate(3), resul.getInt(4), resul.getString(5), resul.getString(6), resul.getString(7), resul.getString(8));
            }
            num_Ref = registro.getNum_ref();
            label_numRef.setText(Integer.toString(numRef));
            spn_refVisita.setValue(registro.getRef_visita());
            calendar_fecha.setDatoFecha(registro.getFechaReal());
            spn_Cantidad.setValue(registro.getCantidad());
            cmb_refSexo.setSelectedItem(registro.getRef_sexo());
            cmb_rangoEdad.setSelectedItem(registro.getRef_rangoEdad());
            boolean inter = false;
            inter = (registro.getProcedencia_Internacional().equalsIgnoreCase("Y") ? true : false);
            chb_Internacional.setSelected(inter);

        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Visitantes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al tratar de conectar con la base de datos desde el Modificador de Visitantes");
        }

        ConexionBaseDatos.desconexionBaseDatos();
        cargarComboBoxProcedencias();
        cmb_procedencia.setSelectedItem(registro.getProcedencia());
    }

    /**
     * Este método rellena el ComboBox del formulario con los ítems relativos a las procedencias. Si el CheckBox del formulario marca procedencia internacional, lo rellena con países. Si no, con comunidades autónomas.
     */
    public void cargarComboBoxProcedencias() {
        try {
            //reseteamos la lista de procedencias y los ítems del combo box
            listaProcedencias = new ArrayList<>();
            cmb_procedencia.removeAllItems();
            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            Statement sentencia = conexion.createStatement();
            String sql;
            if (!chb_Internacional.isSelected()) {
                sql = "SELECT * FROM PROCEDENCIA WHERE TIPO = 'N'";
            } else {
                sql = "SELECT * FROM PROCEDENCIA WHERE TIPO = 'I'";
            }
            ResultSet resul = sentencia.executeQuery(sql);
            //Recorremos el resulSet introducinedo todo en nuestro Array del comboBox
            while (resul.next()) {
                listaProcedencias.add(resul.getString(1));
            }
            resul.close();
            sentencia.close();
            //conexion.close(); lo cerramos a continuación desde la clase
            ConexionBaseDatos.desconexionBaseDatos();

        } catch (SQLException ex) {
            System.out.println("Error al conectar a la base de datos desde el método cargarComboBoxProcedencias");
            Logger.getLogger(F_Base.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmb_procedencia.removeAllItems();
        for (String element : listaProcedencias) {
            cmb_procedencia.addItem(element);
        }
    }

    /**
     * Este método rellena el comboBox del formulario con los sexos registrados en la Base de Datos.
     */
    public void cargarComboBoxSexo() {
        try {
            listaSexo = new ArrayList<>();
            cmb_refSexo.removeAllItems();

            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            Statement sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM TIPOS_SEXO";
            ResultSet resul = sentencia.executeQuery(sql);
            //Recorremos el resulSet introducinedo todo en nuestro Array del comboBox
            while (resul.next()) {
                listaSexo.add(resul.getString(1));
            }
            resul.close();
            sentencia.close();
            //conexion.close(); lo cerramos a continuación desde la clase
            ConexionBaseDatos.desconexionBaseDatos();

        } catch (SQLException ex) {
            System.out.println("Error al conectar a la base de datos desde el método cargarComboBoxTemas");
            Logger.getLogger(F_Base.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmb_refSexo.removeAllItems();
        for (String element : listaSexo) {
            System.out.println("tipos DE SEXO cargados en el comboBox: " + element);
            cmb_refSexo.addItem(element);
        }
    }

    /**
     * Este método carga el comboBox del formulario con los rangos de edad que constan en la Base de Datos.
     */
    public void cargarComboBoxEdad() {
        try {
            listaRangoEdad = new ArrayList<>();
            cmb_rangoEdad.removeAllItems();

            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            Statement sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM RANGO_EDAD";
            ResultSet resul = sentencia.executeQuery(sql);
            //Recorremos el resulSet introducinedo todo en nuestro Array del comboBox
            while (resul.next()) {
                listaRangoEdad.add(resul.getString(1));
            }
            resul.close();
            sentencia.close();
            //conexion.close(); lo cerramos a continuación desde la clase
            ConexionBaseDatos.desconexionBaseDatos();

        } catch (SQLException ex) {
            System.out.println("Error al conectar a la base de datos desde el método cargarComboBoxTemas");
            Logger.getLogger(F_Base.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmb_rangoEdad.removeAllItems();
        for (String element : listaRangoEdad) {
            System.out.println("tipos entradas cargados: " + element);
            cmb_rangoEdad.addItem(element);
        }
    }

    /**
     * Este método gestiona el color de los componentes del formulario en función de las preferencias del usuario.
     */
    public static void establecerColor() {
        ColorInterfaz.dimeColores();
        Color colorFondo = ColorInterfaz.dimeColores()[0];
        Color colorBotones = ColorInterfaz.dimeColores()[1];
        Color colorTexto = ColorInterfaz.dimeColores()[2];

        //Paneles de fondo
        panelFondo.setBackground(colorFondo);
        panelContenedor.setBackground(colorFondo);
        //Botones
        btnModificar.setBackground(colorBotones);
        btnCancelar.setBackground(colorBotones);

        //Textos
        labelTitulo.setForeground(colorTexto);
        label_numRef.setForeground(colorTexto);
        lblCantidad.setForeground(colorTexto);
        lblFecha.setForeground(colorTexto);
        lblProcedencia.setForeground(colorTexto);
        lblProcedenciaInter.setForeground(colorTexto);
        lblRangoEdad.setForeground(colorTexto);
        lblRef.setForeground(colorTexto);
        lblRefVis.setForeground(colorTexto);
        lblSexo.setForeground(colorTexto);
        chb_Internacional.setForeground(colorTexto);
        btnModificar.setForeground(colorTexto);
        btnCancelar.setForeground(colorTexto);
    }
}
