/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modificacionHistoricos;

import Programa.F_Base;
import registros.Registro_Entradas;
import historicos.F_Historico_Visitantes;
import auxiliares.ConexionBaseDatos;
import auxiliares.Fecha;
import configuracion.ColorInterfaz;
import historicos.F_Historico_Entradas;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Esta clase permite modificar los valore sde los registros de venta de entradas existentes en la Base de Datos.
 * Su utilidad es la de corregir datos erróneos.
 * @author Daniel Marcos Muñoz
 */
public class F_Modificar_Entradas extends javax.swing.JFrame {

    int numRef;
    ArrayList<String> listaEntradas;

    /**
     * Creates new form F_Modificar_Entradas
     */
    public F_Modificar_Entradas() {
        initComponents();
        establecerColor();
        setTitle("Centro de Investigación El Fuerte");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        lblRef = new javax.swing.JLabel();
        label_numReg = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        calendar_fecha = new rojeru_san.componentes.RSDateChooser();
        lblEntrada = new javax.swing.JLabel();
        cmb_Entrada = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        spn_Cantidad = new javax.swing.JSpinner();
        lblExenciones = new javax.swing.JLabel();
        spn_Exenciones = new javax.swing.JSpinner();
        lblPrecioTotal = new javax.swing.JLabel();
        spn_precioTotal = new javax.swing.JSpinner();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Modificar Registro");

        panelContenedor.setLayout(new java.awt.GridLayout(6, 2));

        lblRef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRef.setText("Nº Registro:");
        panelContenedor.add(lblRef);

        label_numReg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_numReg.setText("-");
        panelContenedor.add(label_numReg);

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");
        panelContenedor.add(lblFecha);

        calendar_fecha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        calendar_fecha.setFuente(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelContenedor.add(calendar_fecha);

        lblEntrada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEntrada.setText("Entrada:");
        panelContenedor.add(lblEntrada);

        cmb_Entrada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmb_Entrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelContenedor.add(cmb_Entrada);

        lblCantidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad:");
        panelContenedor.add(lblCantidad);

        spn_Cantidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spn_Cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        panelContenedor.add(spn_Cantidad);

        lblExenciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblExenciones.setText("Exenciones:");
        panelContenedor.add(lblExenciones);

        spn_Exenciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spn_Exenciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        panelContenedor.add(spn_Exenciones);

        lblPrecioTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPrecioTotal.setText("Precio Total:");
        panelContenedor.add(lblPrecioTotal);

        spn_precioTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spn_precioTotal.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(9999.99f), Float.valueOf(1.0f)));
        panelContenedor.add(spn_precioTotal);

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar el registro seleccionado?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            String datosActualizacion = "UPDATE REGISTRO_ENTRADAS SET FECHA = '" + Fecha.formateaFecha(calendar_fecha.getDatoFecha()) + "'"
                    + ", TIPO_ENTRADA = '" + (String) cmb_Entrada.getSelectedItem() + "'"
                    + ", CANTIDAD = " + (int) spn_Cantidad.getValue()
                    + ", EXENCIONES = " + (int) spn_Exenciones.getValue()
                    + ", PRECIO_TOTAL = " + (float) spn_precioTotal.getValue()
                    + " WHERE NUM_REF = " + Integer.parseInt(label_numReg.getText());
            System.out.println(datosActualizacion);
            PreparedStatement sentencia;
            try {
                sentencia = conexion.prepareStatement(datosActualizacion);
                sentencia.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Registro modificado con éxito", "Información", 3);
                F_Historico_Entradas.rellenarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(F_Historico_Visitantes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Los datos introducidos no son válidos.\nEl registro NO ha sido modificado.", "Error", 2);
            }
            ConexionBaseDatos.desconexionBaseDatos();
            dispose();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Modificar_Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Modificar_Entradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnCancelar;
    private static javax.swing.JButton btnModificar;
    private rojeru_san.componentes.RSDateChooser calendar_fecha;
    private javax.swing.JComboBox<String> cmb_Entrada;
    private static javax.swing.JLabel labelTitulo;
    private static javax.swing.JLabel label_numReg;
    private static javax.swing.JLabel lblCantidad;
    private static javax.swing.JLabel lblEntrada;
    private static javax.swing.JLabel lblExenciones;
    private static javax.swing.JLabel lblFecha;
    private static javax.swing.JLabel lblPrecioTotal;
    private static javax.swing.JLabel lblRef;
    private static javax.swing.JPanel panelContenedor;
    private static javax.swing.JPanel panelFondo;
    private javax.swing.JSpinner spn_Cantidad;
    private javax.swing.JSpinner spn_Exenciones;
    private javax.swing.JSpinner spn_precioTotal;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método extrae de la Base de Datos los valores que posee el registro seleccionado para modificar, y los carga en un formulario para que el usuario los pueda alterar.
     * @param numRef Recibe por parámetro la clave primaria del registro a modificar.
     */
    public void cargarDatos(int numRef) { //consulta a la base de datos con el NUM_REF de la celda seleccionada en la tabla del registro
        cargarComboBoxEntradas();
        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM REGISTRO_ENTRADAS WHERE NUM_REF = " + numRef;
            ResultSet resul = sentencia.executeQuery(sql);
            Registro_Entradas registro = null;
            while (resul.next()) {
                registro = new Registro_Entradas(resul.getInt(1), resul.getDate(2), resul.getString(3), resul.getInt(4), resul.getInt(5), resul.getFloat(6));
            }
            numRef = registro.getNum_ref();
            label_numReg.setText(Integer.toString(numRef));
            calendar_fecha.setDatoFecha(registro.getFechaReal());
            cmb_Entrada.setSelectedItem(registro.getTipoEntrada());
            spn_Cantidad.setValue(registro.getCantidad());
            spn_Exenciones.setValue(registro.getExcenciones());
            spn_precioTotal.setValue(registro.getPrecioTotal());
        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Visitantes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al tratar de conectar con la base de datos desde el Histórico de Información");
        }

        ConexionBaseDatos.desconexionBaseDatos();
    }

    /**
     * Este método carga el comboBox del formulario de modificación con los diferentes tipos de entrada existentes en la Base de Datos.
     */
    public void cargarComboBoxEntradas() {
        try {

            listaEntradas = new ArrayList<>();
            cmb_Entrada.removeAllItems();

            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            Statement sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM ENTRADA";
            ResultSet resul = sentencia.executeQuery(sql);
            //Recorremos el resulSet introducinedo todo en nuestro Array del comboBox
            while (resul.next()) {
                listaEntradas.add(resul.getString(1));
                System.out.println("Entradas: " + resul.getString(1));
            }
            resul.close();
            sentencia.close();
            //conexion.close(); lo cerramos a continuación desde la clase
            ConexionBaseDatos.desconexionBaseDatos();

        } catch (SQLException ex) {
            System.out.println("Error al conectar a la base de datos desde el método cargarComboBoxMedios");
            Logger.getLogger(F_Base.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmb_Entrada.removeAllItems();
        for (String element : listaEntradas) {
            System.out.println("tipos entradas cargados: " + element);
            cmb_Entrada.addItem(element);
        }
    }

    /**
     * Este método gestiona los colores del formulario de modificación de registros de entradas en función de las preferencias del usuario.
     */
    public static void establecerColor() {
        ColorInterfaz.dimeColores();
        Color colorFondo = ColorInterfaz.dimeColores()[0];
        Color colorBotones = ColorInterfaz.dimeColores()[1];
        Color colorTexto = ColorInterfaz.dimeColores()[2];

        //Paneles de fondo
        panelFondo.setBackground(colorFondo);
        panelContenedor.setBackground(colorFondo);
        //Botones
        btnModificar.setBackground(colorBotones);
        btnCancelar.setBackground(colorBotones);

        //Textos
        labelTitulo.setForeground(colorTexto);
        label_numReg.setForeground(colorTexto);
        lblCantidad.setForeground(colorTexto);
        lblEntrada.setForeground(colorTexto);
        lblFecha.setForeground(colorTexto);
        lblPrecioTotal.setForeground(colorTexto);
        lblRef.setForeground(colorTexto);
        lblExenciones.setForeground(colorTexto);
        btnModificar.setForeground(colorTexto);
        btnCancelar.setForeground(colorTexto);
    }
}
