/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configuracion;

import objetosSimples.TipoEntrada;
import historicos.F_Historico_Informacion;
import auxiliares.ConexionBaseDatos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Esta clase muestra los tipos de entradas existentes en la Base de Datos y ofrece opciones para modificarlas, eliminarlas o crear otras nuevas.
 * @author Daniel Marcos Muñoz
 */
public class F_ConfiguracionEntradas extends javax.swing.JFrame {

    private static ArrayList<TipoEntrada> miLista;
    private static F_Config_NuevaEntrada nuevaEntrada;
    private static F_Config_ModificarEntrada modificarEntrada;

    /**
     * Creates new form F_ConfiguracionEntradaYMerchan
     */
    public F_ConfiguracionEntradas() {
        initComponents();
        establecerColor();
        setTitle("Centro de Investigación El Fuerte");
        setResizable(false);
        extraerDatosDeBase();
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEntradas = new javax.swing.JTable();
        btnNueva = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Configuración de Entradas");

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Concepto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEntradas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaEntradas);

        btnNueva.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnNueva.setText("Nueva");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(btnNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int cantidadFilasSeleccionadas = tablaEntradas.getSelectedRowCount();
        if (cantidadFilasSeleccionadas > 0) {
            ArrayList<String> listaEliminar = new ArrayList<>();
            System.out.println("Cantidad filas seleccionadas: " + cantidadFilasSeleccionadas);
            String indice = "";
            int opcion = JOptionPane.showConfirmDialog(rootPane, "Se van a eliminar " + cantidadFilasSeleccionadas + " registros.\n¿Desea continuar?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                for (int i = 0; i < cantidadFilasSeleccionadas; i++) {
                    indice = (String) tablaEntradas.getValueAt(tablaEntradas.getSelectedRow() + i, 0);
                    listaEliminar.add(indice);
                }
                for (String element : listaEliminar) {
                    eliminarRegistros(element);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar al menos una fila para eliminarla del registro.", "Información", 1);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        if (nuevaEntrada == null) {
            nuevaEntrada = new F_Config_NuevaEntrada();
        }
        nuevaEntrada.setLocationRelativeTo(this);
        nuevaEntrada.setVisible(true);
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int cantCamposSeleccionados = tablaEntradas.getSelectedRowCount();
        if (cantCamposSeleccionados == 1) {
            if (modificarEntrada == null) {
                modificarEntrada = new F_Config_ModificarEntrada();
            }
            String concepto = (String) tablaEntradas.getValueAt(tablaEntradas.getSelectedRow(), 0);
            modificarEntrada.setLocationRelativeTo(this);
            modificarEntrada.setVisible(true);
            modificarEntrada.setConcepto(concepto);
            modificarEntrada.establecerEntrada(concepto);
            modificarEntrada.rellenarPrecio();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una ÚNICA fila para poder modificarla.", "Información", 1);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_ConfiguracionEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_ConfiguracionEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_ConfiguracionEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_ConfiguracionEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_ConfiguracionEntradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnEliminar;
    private static javax.swing.JButton btnModificar;
    private static javax.swing.JButton btnNueva;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel labelTitulo;
    private static javax.swing.JPanel panelFondo;
    private static javax.swing.JTable tablaEntradas;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método realiza una consulta a la Base de Datos y extrae de ella todos los tipos de entradas registrados en la misma.
     */
    
    public static void extraerDatosDeBase() {
        miLista = new ArrayList<>();
        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "SELECT * FROM ENTRADA ORDER BY CONCEPTO ASC";
            ResultSet resul = sentencia.executeQuery(sql);
            while (resul.next()) {
                TipoEntrada entrada = new TipoEntrada(resul.getString(1), resul.getFloat(2));
                miLista.add(entrada);
            }
        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Informacion.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al tratar de conectar con la base de datos desde Configuración de entradas");
        }

        ConexionBaseDatos.desconexionBaseDatos();
    }

    /**
     * Este método rellena los campos del JTable con los tipos de entrada extraídos del método extraerDatosDeBase().
     */
    public static void rellenarTabla() {
        extraerDatosDeBase();
        String matrizDatos[][] = new String[miLista.size()][2];//el segundo número es el número de campos
        for (int i = 0; i < miLista.size(); i++) {
            matrizDatos[i][0] = miLista.get(i).getConcepto();
            matrizDatos[i][1] = Float.toString(miLista.get(i).getPrecio());
        }

        tablaEntradas.setModel(new javax.swing.table.DefaultTableModel(
                matrizDatos,
                new String[]{
                    "CONCEPTO", "PRECIO"
                }
        ));
    }

    /**
     * Este método procede, previa conirmación del usuario, a eliminar de la Base de Datos el tipo de entrada seleccionado.
     * @param indice Es la clave primaria del registro que se pretende eliminar. 
     */
    public void eliminarRegistros(String indice) {
        ConexionBaseDatos.ConexionBaseDatos();
        Connection conexion = ConexionBaseDatos.getConnection();
        Statement sentencia;
        try {
            sentencia = conexion.createStatement();
            String sql;
            sql = "DELETE FROM ENTRADA WHERE CONCEPTO = '" + indice + "'";
            ResultSet resul = sentencia.executeQuery(sql);
            System.out.println("Se ha eliminado el registro " + indice);
        } catch (SQLException ex) {
            Logger.getLogger(F_Historico_Informacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        rellenarTabla();
    }

    /**
     * Este método gestiona los colores de la interfaz que muestra los tipos de entradas existentes.
     */
    public static void establecerColor() {
        ColorInterfaz.dimeColores();
        Color colorFondo = ColorInterfaz.dimeColores()[0];
        Color colorBotones = ColorInterfaz.dimeColores()[1];
        Color colorTexto = ColorInterfaz.dimeColores()[2];

        //Paneles de fondo
        panelFondo.setBackground(colorFondo);

        //Botones
        btnNueva.setBackground(colorBotones);
        btnModificar.setBackground(colorBotones);
        btnEliminar.setBackground(colorBotones);

        //Textos
        labelTitulo.setForeground(colorTexto);
        btnNueva.setForeground(colorTexto);
        btnModificar.setForeground(colorTexto);
        btnEliminar.setForeground(colorTexto);
        if (nuevaEntrada != null) {
            nuevaEntrada.establecerColor();
        }
        if (modificarEntrada != null) {
            modificarEntrada.establecerColor();
        }
    }
}
