/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import auxiliares.ConexionBaseDatos;
import configuracion.ColorInterfaz;
import configuracion.F_ConfiguracionEntradas;
import historicos.F_Historico_Visitantes;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Clase que permite la selección de colores de Fondo, Botones y Texto por parte del usuario.
 * Esta ventana no se ve afectada por esta coloración, para evitar que una selección incorrecta de colores pudiera afectar a su uso.
 * @author Daniel Marcos Muñoz
 */
public class F_PaletaColores extends javax.swing.JFrame {

    Color colorFondo = new Color(0, 0, 0);
    Color colorBotones = new Color(0, 0, 0);
    Color colorTexto = new Color(0, 0, 0);

    int fondoRed, fondoGreen, fondoBlue;
    int botonesRed, botonesGreen, botonesBlue;
    int textoRed, textoGreen, textoBlue;

    /**
     * Creates new form F_Colores
     */
    public F_PaletaColores() {
        initComponents();
        setTitle("Centro de Investigación El Fuerte");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        panelFondo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        btnFondo = new javax.swing.JButton();
        labelColorFondo = new javax.swing.JLabel();
        btnBotones = new javax.swing.JButton();
        labelColorBotones = new javax.swing.JLabel();
        btnTexto = new javax.swing.JButton();
        labelColorTexto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        herramientaColor = new javax.swing.JColorChooser();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitulo.setText("Personalización de colores de la aplicación");

        panelContenedor.setLayout(new java.awt.GridLayout(3, 2));

        btnFondo.setText("Establecer color para fondo");
        btnFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoActionPerformed(evt);
            }
        });
        panelContenedor.add(btnFondo);

        labelColorFondo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelColorFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContenedor.add(labelColorFondo);

        btnBotones.setText("Establecer color para Botones");
        btnBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonesActionPerformed(evt);
            }
        });
        panelContenedor.add(btnBotones);

        labelColorBotones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelColorBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContenedor.add(labelColorBotones);

        btnTexto.setText("Establecer color para Texto");
        btnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextoActionPerformed(evt);
            }
        });
        panelContenedor.add(btnTexto);

        labelColorTexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelColorTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContenedor.add(labelColorTexto);

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(herramientaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(labelTitulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(herramientaColor, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoActionPerformed
        // TODO add your handling code here:
        colorFondo = herramientaColor.getColor();
        fondoRed = colorFondo.getRed();
        fondoGreen = colorFondo.getGreen();
        fondoBlue = colorFondo.getBlue();
        labelColorFondo.setBackground(colorFondo);
        labelColorFondo.setOpaque(true);
    }//GEN-LAST:event_btnFondoActionPerformed

    private void btnBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonesActionPerformed
        colorBotones = herramientaColor.getColor();
        botonesRed = colorBotones.getRed();
        botonesGreen = colorBotones.getGreen();
        botonesBlue = colorBotones.getBlue();
        labelColorBotones.setBackground(colorBotones);
        labelColorBotones.setOpaque(true);

    }//GEN-LAST:event_btnBotonesActionPerformed

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        colorTexto = herramientaColor.getColor();
        textoRed = colorTexto.getRed();
        textoGreen = colorTexto.getGreen();
        textoBlue = colorTexto.getBlue();
        labelColorTexto.setBackground(colorTexto);
        labelColorTexto.setOpaque(true);

    }//GEN-LAST:event_btnTextoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // TODO add your handling code here:
            //conectar a la base de datos y dejar allí la prefedencia guardada

            registrarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(F_PaletaColores.class.getName()).log(Level.SEVERE, null, ex);

        }
        //cartel de cambios guardados
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_PaletaColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_PaletaColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_PaletaColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_PaletaColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_PaletaColores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotones;
    private static javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFondo;
    private static javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnTexto;
    private javax.swing.JColorChooser herramientaColor;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel labelColorBotones;
    private javax.swing.JLabel labelColorFondo;
    private javax.swing.JLabel labelColorTexto;
    private static javax.swing.JLabel labelTitulo;
    private static javax.swing.JPanel panelContenedor;
    private static javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Este método realiza una inserción en la Base de Datos que guarda la selección de colores realizada por el usuario.
     * @throws SQLException Puede lanzar errores de conectividad con la Base de Datos.
     */
    public void registrarDatos() throws SQLException {
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar el registro seleccionado?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            ConexionBaseDatos.ConexionBaseDatos();
            Connection conexion = ConexionBaseDatos.getConnection();
            String datosFondo = "UPDATE COLORES SET RED = " + fondoRed
                    + ", GREEN = " + fondoGreen
                    + ", BLUE = " + fondoBlue
                    + " WHERE CONCEPTO = 'FONDO'";
            System.out.println(datosFondo);
            String datosBotones = "UPDATE COLORES SET RED = " + botonesRed
                    + ", GREEN = " + botonesGreen
                    + ", BLUE = " + botonesBlue
                    + " WHERE CONCEPTO = 'BOTONES'";
            System.out.println(datosBotones);
            String datosTexto = "UPDATE COLORES SET RED = " + textoRed
                    + ", GREEN = " + textoGreen
                    + ", BLUE = " + textoBlue
                    + " WHERE CONCEPTO = 'TEXTO'";
            System.out.println(datosTexto);
            PreparedStatement sentenciaFondo, sentenciaBotones, sentenciaTexto;
            try {
                sentenciaFondo = conexion.prepareStatement(datosFondo);
                sentenciaFondo.executeUpdate();
                sentenciaBotones = conexion.prepareStatement(datosBotones);
                sentenciaBotones.executeUpdate();
                sentenciaTexto = conexion.prepareStatement(datosTexto);
                sentenciaTexto.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Registro modificado con éxito", "Información", 3);
            } catch (SQLException ex) {
                Logger.getLogger(F_Historico_Visitantes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Los datos introducidos no son válidos.\nEl registro NO ha sido modificado.", "Error", 2);
            }

            ConexionBaseDatos.desconexionBaseDatos();
            dispose();
        }

    }
}
